config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'

  post "zipcode" => "home#zipcode"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=84088&distance=25&API_KEY=70278C01-F323-4F5B-81E7-F5AC91D49B3A'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    if @output.empty?
      @final_output = "ERROR"
    elsif  
      !@final_output = "ERROR"
    else
      @final_output = @output[0]["AQI"]
    end

    if @final_output == "Error"
       @api_color = "gray"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = 'Air quality is satisfactory, and air pollution poses little or no risk.'
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = 'Air quality is acceptable. However, there may be a risk for some people, particularly those who are unusually sensitive to air pollution.'
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = 'Members of sensitive groups may experience health effects. The general public is less likely to be affected.'
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = 'Some members of the general public may experience health effects; members of sensitive groups may experience more serious health effects.'
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = 'Health alert: The risk of health effects is increased for everyone.'
    elsif @final_output >= 301
      @api_color = "maroon"
      @api_description = 'Health warning of emergency conditions: everyone is more likely to be affected.'
    end
  end

  def zipcode 
    @zip_query = params[:zipcode]
    if params[:zipcode] == ""
      @zip_query = "You forgot to enter a zipcode!"
    elsif params[:zipcode] 

      require 'net/http'
      require 'json'
  
      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query + '&distance=25&API_KEY=70278C01-F323-4F5B-81E7-F5AC91D49B3A'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)
  
      if @output.empty?
        @final_output = "ERROR"
      elsif  
        !@final_output = "ERROR"
      else
        @final_output = @output[0]["AQI"]
      end
  
      if @final_output == "Error"
         @api_color = "gray"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = 'Air quality is satisfactory, and air pollution poses little or no risk.'
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = 'Air quality is acceptable. However, there may be a risk for some people, particularly those who are unusually sensitive to air pollution.'
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = 'Members of sensitive groups may experience health effects. The general public is less likely to be affected.'
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = 'Some members of the general public may experience health effects; members of sensitive groups may experience more serious health effects.'
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = 'Health alert: The risk of health effects is increased for everyone.'
      elsif @final_output >= 301
        @api_color = "maroon"
        @api_description = 'Health warning of emergency conditions: everyone is more likely to be affected.'
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "WeatherWatch", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        
      </ul>
      </div>
      <div class = 'justify-content-end'>
        <%= form_tag zipcode_path, :method => 'POST' do %>
        <div class="form-inline my-2 my-lg-0">
        <%= text_field_tag 'zipcode', nil, placeholder: "Zipcode", class: 'form-control mr-sm-2'%>
        <%= submit_tag 'Search', class: 'btn btn-outline-success my-2'%>
        <% end %>
        </div>
      </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output%></h1>
  <p class="lead">This is the current ozone air quality.</p>
  <hr class="my-4">
  <p> <%= @api_description %> </p>
  
</div>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output%></h1>
  <p class="lead">This is the current ozone air quality for the <%=@zip_query%>.</p>
  <hr class="my-4">
  <p> <%= @api_description %> </p>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/navbar' %>
  <div class = 'container'>
  </br>
    <%= yield %>
  </div>
  </body>
</html>